"""empty message

Revision ID: 69583928d9ed
Revises: 
Create Date: 2019-08-26 01:35:24.786300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69583928d9ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencers_required')
    op.add_column('campaign', sa.Column('no_of_influencers1', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('no_of_influencers2', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'campaign', 'payments', ['payment'], ['payment_id'])
    op.create_foreign_key(None, 'campaign_posts', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'campaign_type', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'created_table', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'facebook', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.add_column('influencers_involved', sa.Column('range_type', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'influencers_involved', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'influencers_involved', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'instagram', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'interest_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'interest_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'location', 'influencer_details', ['inf_id'], ['influencer_id'])
    op.create_foreign_key(None, 'location', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'location', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'otp_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'otp_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'payments', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'payments', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'posts_done', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.add_column('pricing_details', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('pricing_details', sa.Column('payout', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pricing_details', 'campaign', ['campaign'], ['campaign_id'])
    op.drop_column('pricing_details', 'payout_to_influencers')
    op.drop_column('pricing_details', 'price_to_brand')
    op.drop_column('pricing_details', 'follower_upper_range')
    op.drop_column('pricing_details', 'est_engagement')
    op.drop_column('pricing_details', 'est_videoviews')
    op.drop_column('pricing_details', 'follower_lower_range')
    op.drop_column('pricing_details', 'est_duration')
    op.create_foreign_key(None, 'rel_brand_interest', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_brand_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'spoc_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'twitter', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'youtube', 'influencer_details', ['influencer_id'], ['influencer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube', type_='foreignkey')
    op.drop_constraint(None, 'twitter', type_='foreignkey')
    op.drop_constraint(None, 'spoc_details', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.add_column('pricing_details', sa.Column('est_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('follower_lower_range', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('est_videoviews', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('est_engagement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('follower_upper_range', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('price_to_brand', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('payout_to_influencers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pricing_details', type_='foreignkey')
    op.drop_column('pricing_details', 'payout')
    op.drop_column('pricing_details', 'cost')
    op.drop_constraint(None, 'posts_done', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'instagram', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_column('influencers_involved', 'range_type')
    op.drop_constraint(None, 'facebook', type_='foreignkey')
    op.drop_constraint(None, 'created_table', type_='foreignkey')
    op.drop_constraint(None, 'campaign_type', type_='foreignkey')
    op.drop_constraint(None, 'campaign_posts', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'no_of_influencers2')
    op.drop_column('campaign', 'no_of_influencers1')
    op.create_table('influencers_required',
    sa.Column('inf_req_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range6', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('inf_req_id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
