"""empty message

Revision ID: 7a5ed98cb3e7
Revises: 7c7d4defda29
Create Date: 2019-09-05 16:11:09.681090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a5ed98cb3e7'
down_revision = '7c7d4defda29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('se_admin_login')
    op.create_foreign_key(None, 'campaign', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'campaign', 'payments', ['payment'], ['payment_id'])
    op.create_foreign_key(None, 'campaign_posts', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'campaign_type', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'created_table', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'facebook', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'influencers_involved', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'influencers_involved', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'instagram', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'interest_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'location', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'location', 'influencer_details', ['inf_id'], ['influencer_id'])
    op.create_foreign_key(None, 'location', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'otp_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'otp_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'payments', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'payments', 'brand_details', ['brand_id'], ['brand_id'])
    op.add_column('posts_done', sa.Column('comment_count', sa.String(length=20), nullable=True))
    op.add_column('posts_done', sa.Column('like_count', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'posts_done', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'pricing_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_brand_interest', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_brand_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'spoc_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'twitter', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'youtube', 'influencer_details', ['influencer_id'], ['influencer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube', type_='foreignkey')
    op.drop_constraint(None, 'twitter', type_='foreignkey')
    op.drop_constraint(None, 'spoc_details', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.drop_constraint(None, 'pricing_details', type_='foreignkey')
    op.drop_constraint(None, 'posts_done', type_='foreignkey')
    op.drop_column('posts_done', 'like_count')
    op.drop_column('posts_done', 'comment_count')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'instagram', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'facebook', type_='foreignkey')
    op.drop_constraint(None, 'created_table', type_='foreignkey')
    op.drop_constraint(None, 'campaign_type', type_='foreignkey')
    op.drop_constraint(None, 'campaign_posts', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_table('se_admin_login',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=1000), server_default=sa.text("'no-image.jpg'"), nullable=False),
    sa.Column('ddate', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
