"""empty message

Revision ID: b3cbe8866b83
Revises: e46740ce777e
Create Date: 2019-10-20 13:18:43.978132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3cbe8866b83'
down_revision = 'e46740ce777e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_details', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brand_details', 'location', ['location'], ['location_id'])
    op.add_column('campaign', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'location', ['location'], ['location_id'])
    op.create_foreign_key(None, 'campaign', 'payments', ['payment'], ['payment_id'])
    op.create_foreign_key(None, 'campaign', 'brand_details', ['brand_id'], ['brand_id'])
    op.drop_column('campaign', 'payment_date')
    op.create_foreign_key(None, 'campaign_posts', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'campaign_type', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'created_table', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'facebook', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.add_column('influencer_details', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'influencer_details', 'location', ['location'], ['location_id'])
    op.create_foreign_key(None, 'influencers_involved', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'influencers_involved', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'instagram', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'interest_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.drop_column('location', 'campaign')
    op.drop_column('location', 'inf_id')
    op.drop_column('location', 'brand_id')
    op.create_foreign_key(None, 'otp_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'otp_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'payments', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'payments', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'posts_done', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'pricing_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_brand_interest', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_brand_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'rel_brand_notification', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'influencers_involved', ['inf_inv_id'], ['inf_inv_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'rel_campaign_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'interest_details', ['interest_id'], ['interest_id'])
    op.create_foreign_key(None, 'rel_influencer_interest', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'notifications', ['not_id'], ['not_id'])
    op.create_foreign_key(None, 'rel_influencer_notification', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'spoc_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'twitter', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'youtube', 'influencer_details', ['influencer_id'], ['influencer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube', type_='foreignkey')
    op.drop_constraint(None, 'twitter', type_='foreignkey')
    op.drop_constraint(None, 'spoc_details', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_influencer_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_notification', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.drop_constraint(None, 'rel_brand_interest', type_='foreignkey')
    op.drop_constraint(None, 'pricing_details', type_='foreignkey')
    op.drop_constraint(None, 'posts_done', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.add_column('location', sa.Column('brand_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('inf_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('campaign', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'instagram', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencer_details', type_='foreignkey')
    op.drop_column('influencer_details', 'location')
    op.drop_constraint(None, 'facebook', type_='foreignkey')
    op.drop_constraint(None, 'created_table', type_='foreignkey')
    op.drop_constraint(None, 'campaign_type', type_='foreignkey')
    op.drop_constraint(None, 'campaign_posts', type_='foreignkey')
    op.add_column('campaign', sa.Column('payment_date', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'location')
    op.drop_constraint(None, 'brand_details', type_='foreignkey')
    op.drop_column('brand_details', 'location')
    # ### end Alembic commands ###
